#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 22 20:33:06 2021

@author: jose

"""

classes_dict = {    
                "Avena Alpina": {0: 'Avena Alpina Canela Vaso 250g',
                                 1: 'Avena Alpina Deslactosada Vaso 250ml',
                                 2: 'Avena Alpina Finesse Caja 1000ml',
                                 3: 'Avena Alpina Finesse Vaso 250ml',
                                 4: 'Avena Alpina Original Caja 1000ml',
                                 5: 'Avena Alpina Original Vaso 250g',
                                 6: 'Avena Alpina Others',
                                 7: 'Multiempaque Avena Alpina',
                                 8: 'Multiempaque Avena Alpina Canela Bolsa 200ml X6',
                                 9: 'Multiempaque Avena Alpina Deslactosada Bolsa 200ml X6',
                                 10: 'Multiempaque Avena Alpina Deslactosada Vaso 150g X4',
                                 11: 'Multiempaque Avena Alpina Finesse Vaso 250g X4',
                                 12: 'Multiempaque Avena Alpina Finesse Vaso 250g X6',
                                 13: 'Multiempaque Avena Alpina Original Bolsa 210g X6',
                                 14: 'Multiempaque Avena Alpina Original Vaso 250g X4',
                                 15: '_Others'},
                
                "Arepa": {0:"Arepa De Yuca Don Maiz Paquete 240g", 
                         1:"Arepa Repleta De Queso Don Maiz Paquete 360g",
                         2:"Others"},
                
                "Arequipe": {0: 'Arequipe Alpina',
                             1: 'Arequipe Alpina Vaso 220g',
                             2: 'Arequipe Alpina Vaso 500g',
                             3: '_Others'},
                
               "Alpina Finesse":
                               {0: 'Alpina Finesse',
                                1: 'Bebida De Marañon Alpina Finesse Caja 1000ml',
                                2: 'Crema De Leche Alpina Finesse Caja 200ml',
                                3: 'Finesse Alpina Cereal Musli 170g',
                                4: 'Mousse Finesse Chocolate Vaso 100g',
                                5: 'Multiempaque Finesse Alpina',
                                6: 'Multiempaque Yogurt Finesse Multisabor Vaso 200ml X6',
                                7: 'Yogurt Alpina Finesse Fresa Vaso 200ml',
                                8: 'Yogurt Alpina Finesse Melocoton Vaso 200ml',
                                9: 'Yogurt Alpina Finesse Mora Vaso 200ml',
                                10: 'Yogurt Alpina Finesse Natural Vaso 200ml',
                                11: 'Yogurt Finesse Frutos Rojos Vaso 200ml',
                                12: '_Others'},
               
               "Alpina Finesse Botella":
                                    {0: 'Alpina Finesse Botella',
                                     1: 'Alpina Finesse Others',
                                     2: 'Alpina Finesse Vaso',
                                     3: 'Yogurt Alpina Finesse Fresa Botella 1000ml',
                                     4: 'Yogurt Alpina Finesse Fresa Botella 1700ml',
                                     5: 'Yogurt Alpina Finesse Frutos Rojos Botella 1700ml',
                                     6: 'Yogurt Alpina Finesse Melocoton Botella 1000ml',
                                     7: 'Yogurt Alpina Finesse Melocoton Botella 1700ml',
                                     8: 'Yogurt Alpina Finesse Mora Botella 1000ml',
                                     9: 'Yogurt Alpina Finesse Natural Botella 1000ml',
                                     10: 'Yogurt Alpina Finesse Natural Botella 1700ml',
                                     11: '_Others'},

               "Yogurt Alpina Vaso":{0: 'Kumis Alpina Vaso',
                                    1: 'Multiempaque Kumis Alpina Vaso X4',
                                    2: 'Multiempaque Regeneris Bisabor Vaso X6',
                                    3: 'Multiempaque Regeneris Vaso',
                                    4: 'Multiempaque Yogurt Alpina Original Cocada Vaso X2',
                                    5: 'Multiempaque Yogurt Alpina Original Lulada Vaso X2',
                                    6: 'Multiempaque Yogurt Alpina Original Multisabor Vaso X5',
                                    7: 'Multiempaque Yogurt Alpina Vaso',
                                    8: 'Regeneris Fresa Vaso',
                                    9: 'Regeneris Vaso',
                                    10: 'Yogurt Alpina Deslactosado Fresa Vaso',
                                    11: 'Yogurt Alpina Deslactosado Melocoton Vaso',
                                    12: 'Yogurt Alpina Original Fresa Vaso',
                                    13: 'Yogurt Alpina Original Frutos Rojos Vaso',
                                    14: 'Yogurt Alpina Original Guanabana Vaso',
                                    15: 'Yogurt Alpina Original Melocoton Vaso',
                                    16: 'Yogurt Alpina Original Mora Vaso',
                                    17: 'Yogurt Alpina Original Vaso',
                                    18: '_Others'},
               
               "Yogurt Alpina Botella":
                                    {0: 'Yogurt Alpina Botella',
                                     1: 'Yogurt Alpina Deslactosado Fresa Botella 1000ml',
                                     2: 'Yogurt Alpina Deslactosado Melocoton Botella 1000ml',
                                     3: 'Yogurt Alpina Botella',
                                     4: 'Yogurt Alpina Botella',
                                     5: 'Yogurt Alpina Botella',
                                     6: 'Yogurt Alpina Botella',
                                     7: 'Yogurt Alpina Botella',
                                     8: 'Yogurt Alpina Botella',
                                     9: 'Yogurt Alpina Botella',
                                     10: 'Yogurt Alpina Botella',
                                     11: 'Yogurt Alpina Original Fresa Botella 1000ml',
                                     12: 'Yogurt Alpina Original Fresa Botella 1750ml',
                                     13: 'Yogurt Alpina Original Melocoton Botella 1000ml',
                                     14: 'Yogurt Alpina Original Melocoton Botella 1750ml',
                                     15: 'Yogurt Alpina Original Mora Botella 1750ml',
                                     16: '_Others'},
                                   
                "Yogurt Alpina Bolsa": {0: 'Crema de Leche Alpina Bolsa 1100ml',
                                        1: 'Crema de Leche Alpina Bolsa 200g',
                                        2: 'Kumis Alpina Bolsa 1000g',
                                        3: 'Multiempaque Kumis Alpina Bolsa 150ml X6',
                                        4: 'Yogurt Alpina Bolsa',
                                        5: 'Yogurt Alpina Deslactosado Bolsa 900ml',
                                        6: 'Yogurt Alpina Original Fresa Bolsa 1000ml',
                                        7: 'Yogurt Alpina Original Melocoton Bolsa 1000ml',
                                        8: '_Others'},
                
                "Yogurt Griego Vaso":{0: 'Multiempaque Yogurt Alpina Griego Multisabor Vaso 150g X4',
                                     1: 'Multiempaque Yogurt Alpina Griego Natural Vaso 150g X4',
                                     2: 'Multiempaque Yogurt Alpina Griego Trisabor Vaso 150g X4',
                                     3: 'Multiempaque Yogurt Alpina Griego Vaso 150g X2',
                                     4: 'Multiempaque Yogurt Alpina Griego Vaso 150g X4',
                                     5: 'Multiempaque Yogurt Alpina Griego Vaso 150g X6',
                                     6: 'Multiempaque Yogurt Alpina Griego Vaso 500g X2',
                                     7: 'Yogurt Alpina Griego Coco Vaso 150g',
                                     8: 'Yogurt Alpina Griego Fresa Vaso 150g',
                                     9: 'Yogurt Alpina Griego Limon Vaso 150g',
                                     10: 'Yogurt Alpina Griego Mandarina Vaso 150g',
                                     11: 'Yogurt Alpina Griego Maracuya Vaso 150g',
                                     12: 'Yogurt Alpina Griego Mora-Arandano Vaso 150g',
                                     13: 'Yogurt Alpina Griego Mora-Arandanos Granola Vaso 159g',
                                     14: 'Yogurt Alpina Griego Natural Vaso 150g',
                                     15: 'Yogurt Alpina Griego Natural Vaso 500g',
                                     16: 'Yogurt Alpina Vaso 150g',
                                     17: '_Others'},
               
               "Leche Alpina Bolsa": {0: 'Crema de Leche Alpina Bolsa',
                                    1: 'Leche Alpina Baja En Grasa Bolsa 1.1lt X6',
                                    2: 'Leche Alpina Bolsa',
                                    3: 'Leche Alpina Caja',
                                    4: 'Leche Alpina Descremada Bolsa 1.1lt X6',
                                    5: 'Leche Alpina Descremada Deslactosada Bolsa 1.1lt X6',
                                    6: 'Leche Alpina Deslactosada Bolsa 1.1lt',
                                    7: 'Leche Alpina Deslactosada Bolsa 1.1lt X6',
                                    8: 'Leche Alpina Deslactosada Bolsa 1.3lt X6',
                                    9: 'Leche Alpina Entera Bolsa 1.1lt',
                                    10: 'Leche Alpina Entera Bolsa 1.1lt X6',
                                    11: 'Leche Alpina Entera Bolsa 1.3lt X6',
                                    12: '_Others'},
               
               "Leche Alpina Caja": {0: 'Crema De Leche Alpina Caja 200ml',
                                     1: 'Crema De Leche Alpina Finesse Caja 200ml',
                                     2: 'Crema de Leche Alpina Caja UAT 200ml Nueva',
                                     3: 'Leche Alpina Caja 1lt',
                                     4: 'Leche Alpina Descremada Deslactosada Caja 1lt',
                                     5: 'Leche Alpina Deslactosada Caja 200ml',
                                     6: 'Leche Alpina Entera Caja 1lt',
                                     7: 'Leche Alpina Entera Caja 200ml',
                                     8: 'Multiempaque Leche Alpina Caja 1lt X4',
                                     9: 'Multiempaque Leche Alpina Descremada Deslactosada Caja 1lt X4',
                                     10: 'Multiempaque Leche Alpina Deslactosada Caja 1lt Finca La Toscana',
                                     11: 'Multiempaque Leche Alpina Deslactosada Caja 1lt X4',
                                     12: 'Multiempaque Leche Alpina Entera Caja 1lt X4',
                                     13: 'Super Leche Actilife Caja 1000ml',
                                     14: 'Super Leche Actilife Caja 200ml',
                                     15: '_Others'},
               
               "Bonyurt": {0: 'BonYurt Black Vaso 173g',
                            1: 'BonYurt Choco Krispis Vaso 169g',
                            2: 'BonYurt Chokogozzo Vaso 171g',
                            3: 'BonYurt Hersheys Vaso 175g',
                            4: 'BonYurt Piazza Vaso 174g',
                            5: 'Bonyurt Zucaritas 170g',
                            6: 'Mini Bonyurt Chococandy Vaso 100g',
                            7: 'Mini Bonyurt Gomitas Trolli Vaso 100g',
                            8: 'Multiempaque BonYurt',
                            9: 'Multiempaque Bonyurt Bisabor Zucarita-Chococrispi X8',
                            10: 'Multiempaque Bonyurt Choco Krispis Vaso 169g X4',
                            11: 'Multiempaque Bonyurt Zucaritas 170g X4',
                            12: 'Multiempaque Mini BonYurt',
                            13: 'Multiempaque Mini BonYurt Chococandy Vaso 400g X4',
                            14: '_Others'},
                                          
               "Alpin": {0: 'Alpin Caja 200ml',
                         1: 'Alpin Chocolate Botella 300ml',
                         2: 'Alpin Chocolate Caja 200ml',
                         3: 'Alpin Fresa Caja 200ml',
                         4: 'Alpin Vainilla Caja 200ml',
                         5: 'Multiempaque Alpin Chocolate Bolsa 180ml X6',
                         6: 'Multiempaque Alpin Chocolate Botella 300ml X4',
                         7: 'Multiempaque Alpin Chocolate Caja 200ml X6',
                         8: 'Multiempaque Alpin Fresa Bolsa 180g X6',
                         9: 'Multiempaque Alpin Fresa-Chocolate Bolsa 180g X6',
                         10: 'Multiempaque Alpin Multisabor Caja 200ml X6',
                         11: '_Others'},
               
               "Alpinette": {0:'Alpinette Cereza Vaso 140g',
                             1:'Alpinette Fresa Vaso 140g',
                             2:'Alpinette Maracuya Vaso 140g',
                             3:'Alpinette Melocoton Vaso 140g',
                             4:'Alpinette Mora Vaso 140g',
                             5:'Multiempaque Alpinette Cereza Vaso 140g X3',
                             6:'_Others'},

               "Alpinito":  {0: 'Alpinito Fresa Vaso 45ml',
                             1: 'Alpinito Max Fresa Vaso 90ml',
                             2: 'Alpinito Max Frutos y Galleta Vaso 90ml',
                             3: 'Alpinito Max Mora Vaso 90ml',
                             4: 'Alpinito Melocoton Vaso 45ml',
                             5: 'Alpinito Mora Vaso 45ml',
                             6: 'Alpinito/Multiempaque/Cuchareable',
                             7: 'Multiempaque Alpinito Fresa Vaso 45ml X4',
                             8: 'Multiempaque Alpinito Max Fresa 90ml X4',
                             9: 'Multiempaque Alpinito Max Frutos y Galleta 90ml X4',
                             10: 'Multiempaque Alpinito Max Mora 90ml X4',
                             11: 'Multiempaque Alpinito Melocoton Vaso 45ml X4',
                             12: 'Multiempaque Alpinito Mora Vaso 45ml X4',
                             13: 'Multiempaque Alpinito Multisabor Vaso 45ml X12',
                             14: 'Yogo Yogo Alpina Cuchareable Fresa Vaso 100ml',
                             15: 'Yogo Yogo Alpina Cuchareable Melocoton Vaso 100ml',
                             16: '_Others'},
               
               "Gelatina": {0: 'Boggy Cereza Vaso 108g',
                             1: 'Boggy Fresa Vaso 108g',
                             2: 'Boggy Mora Vaso 108g',
                             3: 'Boggy Naranja Vaso 108g',
                             4: 'Boggy Premio Cereza Vaso 108g',
                             5: 'Boggy Premio Fresa Vaso 108g',
                             6: 'Boggy Premio Mora Vaso 108g',
                             7: 'Boggy Premio Naranja Vaso 108g',
                             8: 'Boggy Uva Vaso 108g',
                             9: 'Gelatina Finesse Frutos Amarillos 108g',
                             10: 'Gelatina Finesse Frutos Rojos 108g',
                             11: 'Gelatina Finesse Uva Verde 108g',
                             12: 'Multiempaque Gelatina Boggy Fresa Vaso 108g X4',
                             13: 'Multiempaque Gelatina Boggy Premio Vaso 108g X6',
                             14: 'Multiempaque Gelatina Finesse Uva Verde Caja X3',
                             15: '_Others'},
               
                "Baby Gu": {0: 'Compota Alpina Baby Gu',
                            1: 'Compota Alpina Natural Banano Baby Gu Vaso 113g',
                            2: 'Compota Alpina Natural Frutas Mixtas Baby Gu Vaso 113g',
                            3: 'Compota Alpina Natural Manzana Baby Gu Vaso 113g',
                            4: 'Compota Alpina Natural Manzana-Mango Baby Gu Vaso 113g',
                            5: 'Compota Alpina Natural Pera Baby Gu Vaso 113g',
                            6: 'Multiempaque Compota Baby Gu Vaso',
                            7: 'Multiempaque Yogurt Baby Gu Vaso 113g X6',
                            8: 'Yogurt Alpina Baby Gu Vaso 113g',
                            9: 'Yogurt Alpina Natural Baby Gu Vaso 113g',
                            10: 'Yogurt Alpina Vainilla Baby Gu Vaso 113g',
                            11: 'Yogurt Alpina Vainilla Cereal Baby Gu Vaso 105g',
                            12: '_Others'},
               
               "Frutto Botella-Caja": {0: 'Fruper Caja 200ml',
                                        1: 'Frutto 100% Jugo de Naranja 1000 ml',
                                        2: 'Frutto Alpina Litteral Botella 305ml',
                                        3: 'Frutto Pera Botella 300ml',
                                        4: 'Multiempaque Fruper Multisabor Caja 200ml X6',
                                        5: 'Multiempaque Fruper Multisabor Caja 200ml X9',
                                        6: 'Multiempaque Frutto Multisabor Caja 200ml x10',
                                        7: 'Multiempaque Nectar Frutto',
                                        8: 'Multiempaque Nectar Frutto Multisabor Caja 200ml X6',
                                        9: 'Nectar Frutto Caja',
                                        10: 'Nectar Frutto Durazno Botella',
                                        11: 'Nectar Frutto Durazno Botella 300ml',
                                        12: 'Nectar Frutto Durazno Caja 1000ml',
                                        13: 'Nectar Frutto Manzana Botella 300ml',
                                        14: 'Nectar Frutto Manzana Botella 965ml',
                                        15: 'Nectar Frutto Manzana Caja 1000ml',
                                        16: 'Nectar Frutto Manzana Caja 200ml',
                                        17: 'Nectar Frutto Pera Caja 1000ml',
                                        18: 'Nectar Frutto Pera Caja 200ml',
                                        19: '_Others'},
               
               "Soka Botella": {0: 'Soka Mandarina Botella 300ml',
                                1: 'Soka Mango Botella 300ml',
                                2: 'Soka Maracuya Botella 300ml',
                                3: 'Soka Mora Botella 300ml',
                                4: 'Soka Zero Mandarina Botella 300ml',
                                5: 'Soka Zero Mango Botella 300ml',
                                6: 'Soka Zero Maracuya Botella 300ml',
                                7: 'Soka Zero Mora Botella 300ml',
                                8: '_Others'},              
               
               "Yox Botella": {0: 'Multiempaque Yox',
                                1: 'Yox Fresa Botella 100ml',
                                2: 'Yox Fresa Botella Sin Azucar 100ml',
                                3: 'Yox Melocoton Botella 100ml',
                                4: 'Yox Melocoton Sin Azucar Botella 100ml',
                                5: 'Yox Multifruta Botella 100ml',
                                6: 'Yox Naranja Miel Botella 100ml',
                                7: 'Yox Vainilla Botella 100ml',
                                8: '_Others'},

              
               "Yogo Yogo Alpina Vaso-Caja": 
                                        {0: 'Multiempaque Yogo Yogo Alpina Bisabor Caja 200ml X6',
                                         1: 'Multiempaque Yogo Yogo Alpina Multisabor Vaso 150ml X4',
                                         2: 'Yogo Yogo Alpina Bolsa',
                                         3: 'Yogo Yogo Alpina Botella',
                                         4: 'Yogo Yogo Alpina Fresa Caja 200ml',
                                         5: 'Yogo Yogo Alpina Fresa Vaso 150ml',
                                         6: 'Yogo Yogo Alpina Melocoton Caja 200ml',
                                         7: 'Yogo Yogo Alpina Melocoton Vaso 150ml',
                                         8: 'Yogo Yogo Alpina Mora Vaso 150ml',
                                         9: 'Yogo Yogo Cereal Chocolate 130g',
                                         10: 'Yogo Yogo Cereal Fresa 130g',
                                         11: 'Yogo Yogo Cereal Natural 130g',
                                         12: '_Others'},
               
               "Yogo Yogo Alpina Bolsa": 
                                    {0: 'Maxi Yogo Yogo Alpina Fresa Bolsa 1100ml',
                                     1: 'Maxi Yogo Yogo Alpina Melocoton Bolsa 1100ml',
                                     2: 'Maxi Yogo Yogo Alpina Mora Bolsa 1100ml',
                                     3: 'Multiempaque Yogo Yogo Alpina Bolsa 1000ml X3',
                                     4: 'Multiempaque Yogo Yogo Multisabor Bolsa 150ml X8',
                                     5: 'Yogo Yogo Alpina Botella',
                                     6: 'Yogo Yogo Alpina Caja',
                                     7: 'Yogo Yogo Alpina Fresa Bolsa 1000ml',
                                     8: 'Yogo Yogo Alpina Fresa Bolsa 150ml',
                                     9: 'Yogo Yogo Alpina Melocoton Bolsa 1000ml',
                                     10: 'Yogo Yogo Alpina Melocoton Bolsa 150ml',
                                     11: 'Yogo Yogo Alpina Mora Bolsa 1000ml',
                                     12: 'Yogo Yogo Alpina Mora Bolsa 150ml',
                                     13: 'Yogo Yogo Alpina Vaso',
                                     14: '_Others'},
               
               "Yogo Yogo Alpina Botella": {0: 'Multiempaque Yogo Yogo Alpina Botella',
                                            1: 'Yogo Yogo Alpina Bolsa',
                                            2: 'Yogo Yogo Alpina Caja',
                                            3: 'Yogo Yogo Alpina Fresh Lulo Botella 185ml',
                                            4: 'Yogo Yogo Alpina Fresh Maracuya Botella 185ml',
                                            5: 'Yogo Yogo Alpina Vaso',
                                            6: 'Yogo Yogo Premio Fresa 150ml',
                                            7: 'Yogo Yogo Premio Melocoton 150ml',
                                            8: 'Yogo Yogo Premio Mora 150ml',
                                            9: '_Others'},
               
               "Mantequilla":  {0: 'Mantequilla Alpina',
                                1: 'Mantequilla Alpina Con Sal 125g',
                                2: 'Mantequilla Alpina Con Sal 250g',
                                3: 'Mantequilla Alpina Sin Sal 125g',
                                4: 'Mantequilla Alpina Sin Sal 250g',
                                5: 'Mantequilla Alpina Sin Sal 500g',
                                6: '_Others'},
               
               "Multiempaque Yox Botella": {0: 'Multiempaque Yox Fresa Botella 100ml X8',
                                            1: 'Multiempaque Yox Multisabor Botella 100ml X12',
                                            2: 'Multiempaque Yox Multisabor Botella 100ml X4',
                                            3: 'Multiempaque Yox Multisabor Botella 100ml X8',
                                            4: 'Multiempaque Yox Multisabor Sin Azucar Botella 100ml X8',
                                            5: 'Multiempaque Yox Vainilla Botella 100ml X8',
                                            6: 'Yox Botella 100ml',
                                            7: '_Others'},
               
               "Multiempaque Yogo Yogo Bolsa": {0:"Kumis Alpina Bolsa 1000g",
                                                1:"Multiempaque Yogo Yogo Multisabor Bolsa 150g X8",
                                                2:"Yogo Yogo Alpina Fresa Bolsa 1000ml",
                                                3:"Yogo Yogo Alpina Melocoton Bolsa 1000ml", 
                                                4:"Yogo Yogo Alpina Mora Bolsa 1000ml",                                       
                                                5:"Yogo Yogo Fresa Bolsa 150g",
                                                6:"_Others"},
                                    
               "Multiempaque Alpina Vaso": 
                                      {0: 'Kumis Alpina Vaso',
                                       1: 'Multiempaque Kumis Alpina Vaso X4',
                                       2: 'Multiempaque Regeneris Bisabor Vaso X6',
                                       3: 'Multiempaque Regeneris Vaso',
                                       4: 'Multiempaque Yogurt Alpina Original Cocada Vaso X2',
                                       5: 'Multiempaque Yogurt Alpina Original Lulada Vaso X2',
                                       6: 'Multiempaque Yogurt Alpina Original Multisabor Vaso X5',
                                       7: 'Multiempaque Alpina Vaso',
                                       8: 'Multiempaque Alpina Vaso',
                                       9: 'Multiempaque Alpina Vaso',
                                       10: 'Multiempaque Alpina Vaso',
                                       11: 'Multiempaque Alpina Vaso',
                                       12: 'Multiempaque Alpina Vaso',
                                       13: 'Multiempaque Alpina Vaso',
                                       14: 'Multiempaque Alpina Vaso',
                                       15: 'Multiempaque Alpina Vaso',
                                       16: 'Multiempaque Alpina Vaso',
                                       17: 'Multiempaque Alpina Vaso',
                                       18: '_Others'},
            
                                   
            "Queso Alpina": {0: 'Multiempaque Queso Finesse Snack 30g X6',
                                1: 'Queso Alpina',
                                2: 'Queso Alpina Brie 135g',
                                3: 'Queso Alpina Campesino Bloque 250g',
                                4: 'Queso Alpina Finesse',
                                5: 'Queso Alpina Finesse 7 Tajadas 105g',
                                6: 'Queso Alpina Holandes',
                                7: 'Queso Alpina Holandes 15 Tajadas',
                                8: 'Queso Alpina Mozarella 15 Tajadas 240g',
                                9: 'Queso Alpina Mozarella 25 Tajadas 400g',
                                10: 'Queso Alpina Para Fondue 400g',
                                11: 'Queso Alpina Parmesano Rallado Bolsa 100g',
                                12: 'Queso Alpina Parmesano Rallado Bolsa 250g',
                                13: 'Queso Alpina Parmesano Rallado Bolsa 40g',
                                14: 'Queso Alpina Parmesano Rallado Bolsa 500g',
                                15: 'Queso Alpina Sabana 15 Tajadas 240g',
                                16: 'Queso Alpina Sabana 25 Tajadas 400g',
                                17: 'Queso Alpina Sabana 7 Tajadas 91g',
                                18: 'Queso Alpina Tilsit',
                                19: 'Queso Finesse 15 Tajadas',
                                20: 'Queso Finesse 30 Tajadas',
                                21: 'Queso Holandes Alpina Bloque 250g',
                                22: '_Others'},
                                    
            "Queso Alpina Vaso": 
                                {0: 'Quesito Alpina 185g',
                                 1: 'Quesito Alpina 375g',
                                 2: 'Queso Alpina Cremosino Vaso 200g',
                                 3: 'Queso Alpina Cremosino Vaso 380g',
                                 4: 'Queso Alpina Vaso',
                                 5: 'Queso Crema Finesse Vaso 200g',
                                 6: '_Others'}
               }


grouped_classes = ['Alpina Finesse',
                   'Alpina Finesse Botella',
                    'Alpin',
                    "Alpinette",
                    "Alpinito",
                    'Arepa',
                    'Arequipe',
                    'Avena Alpina',
                    "Baby Gu",
                    'Bonyurt',
                    "Frutto Botella-Caja",
                    'Gelatina',
                    'Leche Alpina Bolsa',
                    'Leche Alpina Caja',
                    'Mantequilla',
                    "Multiempaque Alpina Vaso",
                    'Multiempaque Yox Botella',
                    'Queso Alpina',
                    'Queso Alpina Vaso',
                    "Soka Botella",
                    'Yogurt Alpina Vaso', 
                    'Yogurt Alpina Bolsa',
                    'Yogurt Alpina Botella',
                    'Yogurt Griego Vaso', 
                    "Yox Botella",   
                    "Yogo Yogo Alpina Vaso-Caja",
                    "Yogo Yogo Alpina Bolsa",
                    "Yogo Yogo Alpina Botella", 
                   ]

models_dict = {'Alpina Finesse':'Finesse',
               "Alpina Finesse Botella":"FinesseBotella",
               'Alpin':'Alpin',
               "Alpinette":"Alpinette",
               "Alpinito":"Alpinito",
               'Arepa':'Arepa',
               'Arequipe':'Arequipe',
               'Avena Alpina':"Avena",
               "Baby Gu":"BabyGu",
               'Bonyurt':'Bonyurt',
               "Frutto Botella-Caja":"FruttoBotellaCaja",
               'Gelatina':'Gelatina',
               'Leche Alpina Bolsa':'LecheBolsa',
               'Leche Alpina Caja':'LechesCaja',
               "Multiempaque Alpina Vaso":"YogurtAlpina",
               'Mantequilla':'Mantequilla',
               'Multiempaque Yox Botella':"YoxMultiempaque",
               'Queso Alpina':'Quesos',
               'Queso Alpina Vaso':'QuesoVaso',
               "Soka Botella":"Soka",
               'Yogurt Alpina Vaso':'YogurtAlpina', 
               'Yogurt Alpina Bolsa':"YogurtBolsa",
               'Yogurt Alpina Botella':"YogurtBotella",
               'Yogurt Griego Vaso':"Griego", 
               "Yox Botella":"YoxBotella",   
               "Yogo Yogo Alpina Vaso-Caja":"YogoVasoCaja",
               "Yogo Yogo Alpina Bolsa":"YogoBolsa",
               "Yogo Yogo Alpina Botella":"YogoBotella",                
                }
