[server]
port = 8020
baseUrlPath = 'dashboard'
folderWatchBlacklist = ['img']

[runner]

magicEnabled = true

[theme]
primaryColor="#101010"
backgroundColor="#e6eae5"
secondaryBackgroundColor="#456d50"
textColor="#000000"
